# ---------------------------------------------------------------------------
# compute module -- inputs
# ---------------------------------------------------------------------------

variable "project_name" {
  description = "Short project identifier used in resource names + tags."
  type        = string
}

# ---------- Wiring from the networking module -----------------------------

variable "subnet_id" {
  description = "Public subnet ID where the EC2 instance is launched."
  type        = string
}

variable "security_group_ids" {
  description = "Security groups attached to the EC2 instance. Expect the web SG (HTTP + SSH)."
  type        = list(string)
}

# ---------- EC2 configuration ---------------------------------------------

variable "instance_type" {
  description = "EC2 instance type. t3.micro is enough for a Hello World Flask app."
  type        = string
  default     = "t3.micro"
}

variable "key_name" {
  description = "Name of an EXISTING AWS key pair for SSH access. Not generated by Terraform."
  type        = string
}

# ---------- GitHub Actions / OIDC -----------------------------------------

variable "github_repo" {
  description = "GitHub repo in 'owner/name' form. Used to scope the OIDC trust policy so ONLY this repo can assume the IAM role."
  type        = string

  validation {
    condition     = can(regex("^[^/]+/[^/]+$", var.github_repo))
    error_message = "github_repo must be in 'owner/name' format (e.g. 'owaisrizvi97/idalko-exalate')."
  }
}
